### ISSUE TITLE
[SoD] Trap BDTR01.SPL should not crash the game if the trigger is immune to Slow

### ISSUE THREAD

**Issue by Argent77** [Gibberlings3/EE_Fixpack#35]
__How to reproduce:__
- Create a new SoD game with a Monk character
  - alternatively, create an arbitrary character and equip the Ring of Free Action (`BDRING09`)
- `C:MoveToArea("BD5000")`
- `Ctrl-J` to top-right region of the map (around coordinate [4500.1275])
- Move your character to the left to trigger the trap

__Observed:__
Triggering the trap crashes the game.

__Expected:__
The trap should apply the damage part but skip both Slow and opcode 215 effects due to opcode 324 filter.

**Comment by CamDawg** [comment]
Thanks for this. Bubb had reported this error at the code level due to a confluence of events--basically, the game will crash if you use a 324 with a trap-triggered spell that lacks a name. It crashes trying to source a name for the resistance string.

**Comment by CamDawg** [comment]
Oh, and it can happen with a 318 as well. I was unable to repro it with 318, but both Bubb and another Discord user were able to get crashes intermittently.

**Comment by CamDawg** [comment]
Fixed by the above commit, and the oopsie followup commit: https://github.com/CamDawg/EE_Fixpack/commit/9cf4683394d2c229a58b1dc61f94fe2eec230681
