### ISSUE TITLE
[SoD] Chapter 13: Reunification with Imoen and canon party should work

### ISSUE THREAD

**Issue by Argent77** [Gibberlings3/EE_Fixpack#39]
__How to reproduce:__
- Start a new SoD game with an arbitrary character
- When you have control over the party:
  - Pause the game
  - Kick everyone out (`Ctrl-K`)
  - `C:MoveToArea("BD6000")`
  - Unpause the game
- `Ctrl-J` to the map exit (around coordinate [1775.3125])
- Execute console command: `C:SetGlobal("bd_plot","global",640);C:SetGlobal("bd_player_exiled","global",1);C:SetGlobal("chapter","global",13)`
- Leave the map

__Expected:__
Imoen initiates her intended SoD dialog, followed by a scripted event to rejoin with the canon party.

__Observed:__
Imoen initiates her BG1 Candlekeep dialog. There is no further plot progress afterwards.

__Notes:__
This is caused by an erroneous string replacement of `"bdimoen"` -> `"imoen"` in the CreateCreature() action of BD6200.BCS, line 208.

**Comment by CamDawg** [comment]
Lazy REPLACE_TEXTUALLY from me. This is fixed in https://github.com/Gibberlings3/EE_Fixpack/commit/5adb1f15d33df4612a0bee46e6910cae946cff67
