### ISSUE TITLE
[BG2] Shadow creatures should be affected by the light crystal traps in the Shadow Temple 

### ISSUE THREAD

**Issue by Argent77** [Gibberlings3/EE_Fixpack#40]
__How to reproduce:__
- `C:MoveToArea("AR1401")` (Shadow Temple interior)
- `Ctrl-J` or walk to the crystal lamp (around coordinate [850.1350])
- Wait for the summoned Shadows to enter the light trap

__Expected:__
Shadows should be killed when they enter the region around the crystal lamp.

__Observed:__
Shadows produce the "Holy Might" pillar animation but are otherwise unaffected by the trap spell.

__Notes:__
Script SPSHADOM.BCS applies spell SPWI023.SPL specifically to Shadows. However, the spell contains a 324 effect that excludes targets immune to Death effects (which Shadows are). The same issue applies to the crystal trap on the Shadow Temple exterior map (AR1404).

**Comment by CamDawg** [comment]
Since spwi023 only gets applied in these circumstances, the 324 shouldn't be added. Fixed in commit https://github.com/Gibberlings3/EE_Fixpack/commit/735dbdc28014b7fe85d4a4f82ef211ef09693b52
